### ISSUE TITLE
Upgrading from geo 3.3.3 and geo_postgis 3.3.1 to latest results in argument error

### ISSUE THREAD

**Issue by muki** [bryanjos/geo_postgis#110]
I'm not sure if this issue should be filed in `geo` but if I upgrade my dependencies to latest I start getting errors when doing a `st_dwithin_in_meters` query. It all works if I stay at 3.3.3 and 3.3.1

I'm unfortunately not very well versed in either Elixir/Phoenix or PostGIS, so it's quite possible I'm doing something silly. I read through the changelogs but still have no clue how to go about fixing this. Once at latest, this is the log with the error:

```
[debug] QUERY ERROR source="rooms" db=1.7ms queue=1.2ms idle=249.7ms
phoenix_1  | SELECT r0."id", r0."name", r0."category_id", r0."lat", r0."lng", r0."coordinates", r0."radius", r0."description", r0."inserted_at", r0."updated_at" FROM "rooms" AS r0 WHERE (ST_DWithin(r0."coordinates"::geography, $1::geography, r0."radius")) ORDER BY ST_Distance(r0."coordinates"::geography, $2::geography) LIMIT 5 [%Geo.Point{coordinates: {"14.4912463", "46.0700097"}, properties: %{}, srid: 4326}, %Geo.Point{coordinates: {"14.4912463", "46.0700097"}, properties: %{}, srid: 4326}]
phoenix_1  | [info] Sent 500 in 39ms
phoenix_1  | [error] #PID<0.1458.0> running KjerSiWeb.Endpoint (connection #PID<0.1457.0>, stream id 1) terminated
phoenix_1  | Server: 192.168.1.129:4000 (http)
phoenix_1  | Request: GET /api/rooms?lat=46.0700097&lng=14.4912463
phoenix_1  | ** (exit) an exception was raised:
phoenix_1  |     ** (ArgumentError) argument error
phoenix_1  |         (geo 3.4.2) lib/geo/wkb/encoder.ex:61: Geo.WKB.Encoder.do_encode/2
phoenix_1  |         (geo 3.4.2) lib/geo/wkb/encoder.ex:48: Geo.WKB.Encoder.encode!/2
phoenix_1  |         (kjer_si 0.1.0) lib/geo_postgis/extension.ex:76: KjerSi.PostgresTypes."Elixir.Geo.PostGIS.Extension"/1
phoenix_1  |         (kjer_si 0.1.0) deps/postgrex/lib/postgrex/type_module.ex:897: KjerSi.PostgresTypes.encode_params/3
phoenix_1  |         (postgrex 0.15.8) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
phoenix_1  |         (db_connection 2.4.0) lib/db_connection.ex:1205: DBConnection.encode/5
phoenix_1  |         (db_connection 2.4.0) lib/db_connection.ex:1305: DBConnection.run_prepare_execute/5
phoenix_1  |         (db_connection 2.4.0) lib/db_connection.ex:1409: DBConnection.run/6
phoenix_1  |         (db_connection 2.4.0) lib/db_connection.ex:574: DBConnection.parsed_prepare_execute/5
phoenix_1  |         (db_connection 2.4.0) lib/db_connection.ex:566: DBConnection.prepare_execute/4
phoenix_1  |         (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:690: Ecto.Adapters.SQL.execute!/4
phoenix_1  |         (ecto_sql 3.6.1) lib/ecto/adapters/sql.ex:682: Ecto.Adapters.SQL.execute/5
phoenix_1  |         (ecto 3.6.1) lib/ecto/repo/queryable.ex:224: Ecto.Repo.Queryable.execute/4
phoenix_1  |         (ecto 3.6.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
phoenix_1  |         (kjer_si 0.1.0) lib/kjer_si/rooms.ex:265: KjerSi.Rooms.get_rooms_around_point/1
phoenix_1  |         (kjer_si 0.1.0) lib/kjer_si_web/controllers/room_controller.ex:24: KjerSiWeb.RoomController.index/2
phoenix_1  |         (kjer_si 0.1.0) lib/kjer_si_web/controllers/room_controller.ex:1: KjerSiWeb.RoomController.action/2
phoenix_1  |         (kjer_si 0.1.0) lib/kjer_si_web/controllers/room_controller.ex:1: KjerSiWeb.RoomController.phoenix_controller_pipeline/2
phoenix_1  |         (phoenix 1.5.8) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
phoenix_1  |         (kjer_si 0.1.0) lib/kjer_si_web/endpoint.ex:1: KjerSiWeb.Endpoint.plug_builder_call/2
```

The relevant bits of code seem to be:

`room_controller.ex`
```
def index(conn, params) do
    changeset = room_index(params)

    if changeset.valid? do
      point = %Geo.Point{coordinates: {params["lng"], params["lat"]}, srid: 4326}

      rooms = Rooms.get_rooms_around_point(point)
      render(conn, "index.json", rooms: rooms)
    else
      {:error, changeset}
    end
  end
```

and `rooms.exs`
```
  def get_rooms_around_point(point) do
    query =
      from room in Room,
        where: st_dwithin_in_meters(room.coordinates, ^point, room.radius),
        order_by: [asc: st_distance_in_meters(room.coordinates, ^point)],
        limit: 5

    query
    |> Repo.all()
    |> Repo.preload(:users)
  end
```

**Comment by RoyalMist** [comment]
Got the same must be linked to this : Geo.PostGIS.Extension now uses the :binary format instead of :text I am investigating and keep you posted if I find something.

**Comment by RoyalMist** [comment]
It is not an issue, Geo is stricter than before : 
eg : point = %Geo.Point{coordinates: {"46.23333", "7.36667"}, srid: 4326} fails as WKB.encode due to long and lat typed as string. Use numbers instead : point = %Geo.Point{coordinates: {46.23333, 7.36667}, srid: 4326}. The API I am using is returning string lat and long so I just have to parse them (I think you too)

**Comment by muki** [comment]
Thank you! Parsing the inputs was exactly what I needed to do.
