### ISSUE TITLE
Compatibility with Phoenix 1.4

### ISSUE THREAD

**Issue by Sanchezdav** [bryanjos/geo_postgis#23]
I'm following the README and I got this error when I run the migrations
```
$ mix ecto.migrate
** (MatchError) no match of right hand side value: {:error, {:poison, {'no such file or directory', 'poison.app'}}}
    (ecto_sql) lib/mix/ecto_sql.ex:9: Mix.EctoSQL.ensure_started/2
    (ecto_sql) lib/mix/tasks/ecto.migrate.ex:103: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```
I think this is an incompatibility in Phoenix 1.4 since they changed from Poison to Jason

**Comment by cultofmetatron** [comment]
I have this working with 1.4 atm

Add poison as a dependency then create a file postgres_types.ex in your lib folder
```

Postgrex.Types.define(Scout.PostgresTypes,
  [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
  json: Poison)

```
in your config add the line

```
config :my_app, MyApp.Repo,
  hostname: *******
  username: *******,
  password: *******,
  database: *******,
  types: Scout.PostgresTypes,
  port: 5432,
  pool_size: 15

```

hope it helps!

**Comment by walter** [comment]
You may also need to change use of the type `Geo.Point` in `schema` declarations to `Geo.PostGIS.Geometry`.

**Comment by bryanjos** [comment]
Hopefully this is resolved. Poison shouldn't be required and the json library can be updated via configuration
