### ISSUE TITLE
type `geometry` can not be handled by the types module Ecto.Adapters.Postgres.TypeModule

### ISSUE THREAD

**Issue by digitalcake** [bryanjos/geo_postgis#4]
Getting (but only on my server, not locally)
```
    ** (RuntimeError) type `geometry` can not be handled by the types module Ecto.Adapters.Postgres.TypeModule
        (ecto) lib/ecto/adapters/postgres/connection.ex:79: Ecto.Adapters.Postgres.Connection.prepare_execute/5
        (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
        (ecto) lib/ecto/adapters/sql.ex:426: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:70: Ecto.Repo.Queryable.one/4
        (come_bike) lib/come_bike/events/search.ex:11: ComeBike.Search.find_by_zip_in_n_miles/1
        (come_bike) lib/come_bike/events/events.ex:83: ComeBike.Events.search_rides/1
```

The app in question can be viewed here. https://github.com/ComeBike/come.bike
I also included links to the files relative to each area. 

The issue I'm running into is only an issue on my server, locally I dont have this issue. 

Working with:
* Elixir 1.6.0
* PostgreSQL 9.6 (locally and on server)
* Have enabled postgis
 
mix lock
https://github.com/ComeBike/come.bike/blob/master/mix.lock
```
"geo": {:hex, :geo, "2.1.0", "f9a7a1403dde669c4e3f1885aeb4f3b3fb4e51cd28ada6d9f97463e5da65c04a", [:mix], [{:ecto, "~> 2.1", [hex: :ecto, repo: "hexpm", optional: true]}, {:poison, "~> 3.0", [hex: :poison, repo: "hexpm", optional: true]}], "hexpm"},
"geo_postgis": {:hex, :geo_postgis, "1.1.0", "4c9efc082a8b625c335967fec9f5671c2bc8a0a686f9c5130445ebbcca989740", [:mix], [{:geo, "~> 2.0", [hex: :geo, repo: "hexpm", optional: false]}, {:postgrex, "~> 0.13", [hex: :postgrex, repo: "hexpm", optional: false]}], "hexpm"},
"ecto": {:hex, :ecto, "2.2.8", "a4463c0928b970f2cee722cd29aaac154e866a15882c5737e0038bbfcf03ec2c", [:mix], [{:db_connection, "~> 1.1", [hex: :db_connection, repo: "hexpm", optional: true]}, {:decimal, "~> 1.2", [hex: :decimal, repo: "hexpm", optional: false]}, {:mariaex, "~> 0.8.0", [hex: :mariaex, repo: "hexpm", optional: true]}, {:poison, "~> 2.2 or ~> 3.0", [hex: :poison, repo: "hexpm", optional: true]}, {:poolboy, "~> 1.5", [hex: :poolboy, repo: "hexpm", optional: false]}, {:postgrex, "~> 0.13.0", [hex: :postgrex, repo: "hexpm", optional: true]}, {:sbroker, "~> 1.0", [hex: :sbroker, repo: "hexpm", optional: true]}], "hexpm"},

```

postgres_types.ex
https://github.com/ComeBike/come.bike/blob/master/lib/come_bike/postgres_types.ex
```
Postgrex.Types.define(
  ComeBike.PostgresTypes,
  [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
  json: Poison
)
```

Zips model
https://github.com/ComeBike/come.bike/blob/master/lib/come_bike/events/zip.ex
```
    field(:geom, Geo.Point)
```

migration
https://github.com/ComeBike/come.bike/blob/master/priv/repo/migrations/20180117064455_add_geom_to_zips.exs
```
defmodule ComeBike.Repo.Migrations.AddGeomToZips do
  use Ecto.Migration

  def change do
    alter table("zips") do
      add(:geom, :geometry)
    end

    create(index("zips", [:geom]))
  end
end
```

Thoughts?

**Comment by digitalcake** [comment]
Looks like I forgot the config for prod 🤦‍♂️ 
```  
types: ComeBike.PostgresTypes,
```

**Comment by sergiotapia** [comment]
Bless up :surfer:
