### ISSUE TITLE
Elixir postgis types require encoding for queries?

### ISSUE THREAD

**Issue by chris** [bryanjos/geo_postgis#56]
I'm a bit confused in terms of how pure Postgrex interaction is supposed to work with the PostgrexTypes. The README/docs seem to imply that I should be able to pass an Elixir type as a parameter to a query (per the examples of inserting geometry into a table), e.g. I should be able to pass something like a `%Geo.Point` or `%Geo.Polygon` directly, without needing to encode it as WKB or WKT. However, it doesn't seem to work for me - I have to encode them for it to work. Example iex session showing this follows. 

In the example, I can do this which works (where `box1` and `box2` are `%Geo.Polygon`s:
```
Postgrex.query!(pid, "SELECT ST_Intersection($1, $2)", [Geo.WKT.encode!(box1), Geo.WKT.encode!(box2)])
```

But, as the below example shows (at the very end), doing this fails, saying it expected a binary:
```
Postgrex.query!(pid, "SELECT ST_Intersection($1, $2)", [box1, box2])
```

Here's the example iex session:
```
iex(1)> Postgrex.Types.define(MyApp.PostgrexTypes, [Geo.PostGIS.Extension], [])
{:module, MyApp.PostgrexTypes,
# <full result snipped for clarity>
iex(2)> opts = [hostname: "localhost", username: "postgres", database: "osm", types: MyApp.PostgrexTypes ]
[
  hostname: "localhost",
  username: "postgres",
  database: "osm",
  types: MyApp.PostgrexTypes
]
iex(3)> {:ok, pid} = Postgrex.start_link(opts)
{:ok, #PID<0.403.0>}
iex(4)> box1 = %Geo.Polygon{coordinates: [[{0, 0}, {2, 0}, {2, 2}, {0,2}, {0,0}]]}
%Geo.Polygon{
  coordinates: [[{0, 0}, {2, 0}, {2, 2}, {0, 2}, {0, 0}]],
  properties: %{},
  srid: nil
}
iex(5)> box2 = %Geo.Polygon{coordinates: [[{1, 1}, {3, 1}, {3, 3}, {1,3}, {1,1}]]}
%Geo.Polygon{
  coordinates: [[{1, 1}, {3, 1}, {3, 3}, {1, 3}, {1, 1}]],
  properties: %{},
  srid: nil
}
iex(6)> Postgrex.query!(pid, "SELECT ST_Intersection($1, $2)", [Geo.WKT.encode!(box1), Geo.WKT.encode!(box2)])
%Postgrex.Result{
  columns: ["st_intersection"],
  command: :select,
  connection_id: 14112,
  messages: [],
  num_rows: 1,
  rows: [
    [
      %Geo.Polygon{
        coordinates: [
          [{1.0, 2.0}, {2.0, 2.0}, {2.0, 1.0}, {1.0, 1.0}, {1.0, 2.0}]
        ],
        properties: %{},
        srid: nil
      }
    ]
  ]
}
iex(7)> Postgrex.query!(pid, "SELECT ST_Intersection($1, $2)", [box1, box2])
** (DBConnection.EncodeError) Postgrex expected a binary, got %Geo.Polygon{coordinates: [[{0, 0}, {2, 0}, {2, 2}, {0, 2}, {0, 0}]], properties: %{}, srid: nil}. Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
    deps/postgrex/lib/postgrex/type_module.ex:897: MyApp.PostgrexTypes.encode_params/3
    (postgrex) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection) lib/db_connection.ex:1148: DBConnection.encode/5
    (db_connection) lib/db_connection.ex:1246: DBConnection.run_prepare_execute/5
    (db_connection) lib/db_connection.ex:1342: DBConnection.run/6
    (db_connection) lib/db_connection.ex:540: DBConnection.parsed_prepare_execute/5
    (db_connection) lib/db_connection.ex:533: DBConnection.prepare_execute/4
    (postgrex) lib/postgrex.ex:219: Postgrex.query_prepare_execute/4```

I can of course add the encoding calls to all my code, but the README led me to believe that that shouldn't be necessary, so I wanted to see what the expectation is for queries like this, or what I might be not doing right.

**Comment by bryanjos** [comment]
The configuration looks correct. You are right that you should not have to encode the geo structs and that you should be able to pass them in as is
