### ISSUE TITLE
(Postgrex.QueryError) type `_geometry` can not be handled by the types module GI.PostgresTypes

### ISSUE THREAD

**Issue by MartinElvar** [bryanjos/geo_postgis#97]
I receive the following error after following the installation guide for Ecto.

```
[error] Postgrex.Protocol (#PID<0.1139.0>) disconnected: ** (Postgrex.QueryError) type `_geometry` can not be handled by the types module GI.PostgresTypes
[info] Sent 500 in 21ms
[error] #PID<0.1401.0> running GIWeb.Endpoint (connection #PID<0.1386.0>, stream id 4) terminated
Server: localhost:4000 (http)
Request: GET /utilities/power
** (exit) an exception was raised:
    ** (Postgrex.QueryError) type `_geometry` can not be handled by the types module GI.PostgresTypes
        (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
        (ecto 3.4.6) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
        (ecto 3.4.6) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
        (elixir 1.11.1) lib/enum.ex:1399: Enum."-map/2-lists^map/1-0-"/2
        .....
```

```
Postgrex.Types.define(
  GI.PostgresTypes,
  [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
  json: Jason
)

config :gi, GI.Repo,
  types: GI.PostgresTypes

```

Not sure why it's trying to use _geometry, and not geometry.

Changing lib/geo_postgis/extension.ex to

```
  def matching(_) do
    [type: "geometry", type: "geography", type: "_geometry"]
  end
```

Seems to fix the error.

**Comment by atomkirk** [comment]
I had the same error. I upgraded to 3.4 and now it appears fixed?

**Comment by jsmestad** [comment]
@atomkirk any idea what caused it? I am hitting this error too.
